export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Services } from "./Services";
export { default as About } from "./About";
export { default as Portfolio } from "./Portfolio";
export { default as Testimonials } from "./Testimonials";
export { default as CTA } from "./Cta";
export { default as Footer } from "./Footer";
export { default as SectionTitle } from "./SectionTitle";
